### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Barracuda-AG** [Barracuda-AG/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by murena-og** [comment]
― I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.

**Comment by murena-og** [comment]
Ryu Hoshi (リュウ Ryū)
https://www.facebook.com/profile.php?id=100004808958030
ryuwins@gmail.com
https://twitter.com/denjinryu
https://www.instagram.com/sworn_ryu/
